# Generated by Django 4.0.5 on 2022-10-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
