# Generated by Django 4.0.4 on 2022-07-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='download_game/', verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'способ скачивание игры',
                'verbose_name_plural': 'способы скачивания игры',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Fractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Фракция')),
            ],
            options={
                'verbose_name': 'фракция',
                'verbose_name_plural': 'Фракции',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'руководство',
                'verbose_name_plural': 'Руководства',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KateustaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('creators', models.TextField(verbose_name='Авторы')),
                ('photo', models.ImageField(upload_to='maps', verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'карта',
                'verbose_name_plural': 'Карты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('creators', models.TextField(verbose_name='Авторы')),
                ('photo', models.ImageField(upload_to='mods/', verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'мод',
                'verbose_name_plural': 'Моды',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='online_game', verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'cпособ играть по сети',
                'verbose_name_plural': 'Способы игры по сети',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='WinrateFractionsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фракция')),
                ('games', models.BigIntegerField(verbose_name='Финалок фракции')),
                ('winrate', models.BigIntegerField(verbose_name='Винрейт фракции')),
            ],
            options={
                'verbose_name': 'винрейт фракции',
                'verbose_name_plural': 'Винрейт фракций',
                'ordering': ['-winrate', '-games'],
            },
        ),
        migrations.CreateModel(
            name='WinratePlayersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Игрок')),
                ('games', models.BigIntegerField(verbose_name='Финалок игрока')),
                ('winrate', models.BigIntegerField(verbose_name='Винрейт игрока')),
            ],
            options={
                'verbose_name': 'винрейт игрока',
                'verbose_name_plural': 'Винрейт игроков',
                'ordering': ['-winrate', '-games'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myself', models.CharField(max_length=15, verbose_name='Игрок')),
                ('victory', models.BooleanField(default=True, verbose_name='Победа')),
                ('opponent', models.CharField(max_length=15, verbose_name='Оппонент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('fraction_myself', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fraction_opponent', to='main.fractions', verbose_name='Фракция игрока')),
                ('fraction_opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.fractions', verbose_name='Фракция оппонента')),
            ],
            options={
                'verbose_name': 'отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['myself'],
            },
        ),
    ]
