# Generated by Django 4.0.4 on 2022-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('photo', models.ImageField(blank=True, upload_to='photos/$Y/%m/%d/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'Main',
                'verbose_name_plural': 'Main',
            },
        ),
    ]
