# Generated by Django 4.0.4 on 2022-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['title'],
            },
        ),
        migrations.RenameModel(
            old_name='Fraction',
            new_name='Fractions',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['myself'], 'verbose_name': 'отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterModelOptions(
            name='winratefractionsstats',
            options={'ordering': ['-winrate', '-games'], 'verbose_name': 'винрейт фракции', 'verbose_name_plural': 'Винрейт фракций'},
        ),
        migrations.AlterModelOptions(
            name='winrateplayersstats',
            options={'ordering': ['-winrate', '-games'], 'verbose_name': 'винрейт игрока', 'verbose_name_plural': 'Винрейт игроков'},
        ),
    ]
