# Generated by Django 4.0.4 on 2022-07-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Slug'),
        ),
    ]
