# Generated by Django 4.0.4 on 2022-06-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_players_rename_fraction_fractions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='title',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='main.fractions', verbose_name='Игрок'),
        ),
    ]
