# Generated by Django 4.0.4 on 2022-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_downloadgame_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('creators', models.TextField(verbose_name='Авторы')),
                ('photo', models.ImageField(upload_to='photos/$Y/%m/%d/', verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'Мод',
                'verbose_name_plural': 'Моды',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='downloadgame',
            options={'ordering': ['-title'], 'verbose_name': 'Скачивание игры', 'verbose_name_plural': 'Скачивание игры'},
        ),
    ]
