# Generated by Django 4.0.4 on 2022-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_winrateplayersstats_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadgame',
            name='photo',
            field=models.ImageField(upload_to='download_game/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='home',
            name='photo',
            field=models.ImageField(upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='maps',
            name='photo',
            field=models.ImageField(upload_to='maps', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mods',
            name='photo',
            field=models.ImageField(upload_to='mods/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='online',
            name='photo',
            field=models.ImageField(upload_to='online_game', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='winratefractionsstats',
            name='games',
            field=models.BigIntegerField(verbose_name='Финалок фракции'),
        ),
        migrations.AlterField(
            model_name='winratefractionsstats',
            name='winrate',
            field=models.BigIntegerField(verbose_name='Винрейт фракции'),
        ),
    ]
