# Generated by Django 4.0.4 on 2022-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='photos/$Y/%m/%d/', verbose_name='Изображение')),
                ('url', models.URLField(verbose_name='Cсылка')),
            ],
            options={
                'verbose_name': 'Игра по сети',
                'verbose_name_plural': 'Способы игры по сети',
                'ordering': ['-title'],
            },
        ),
    ]
