# Generated by Django 4.0.4 on 2022-06-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_statisticsplayer_rename_news_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinrateFractionsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фракция')),
                ('games', models.CharField(max_length=3, verbose_name='Сыгрно игр')),
                ('winrate', models.CharField(max_length=3, verbose_name='Винрейт фракции')),
            ],
        ),
        migrations.CreateModel(
            name='WinratePlayersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Игрок')),
                ('games', models.CharField(max_length=3, verbose_name='Сыгрно игр')),
                ('winrate', models.CharField(max_length=3, verbose_name='Винрейт игрока')),
            ],
        ),
        migrations.RemoveField(
            model_name='fractionplayer',
            name='fraction',
        ),
        migrations.DeleteModel(
            name='StatisticsPlayer',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['myself'], 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='myself',
            field=models.CharField(max_length=15, verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='opponent',
            field=models.CharField(max_length=15, verbose_name='Оппонент'),
        ),
        migrations.AlterField(
            model_name='report',
            name='victory',
            field=models.BooleanField(default=True, verbose_name='Победа'),
        ),
        migrations.DeleteModel(
            name='FractionPlayer',
        ),
    ]
