# Generated by Django 4.0.4 on 2022-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_winratefractionsstats_winrateplayersstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinrateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=15, verbose_name='Игрок')),
                ('player_games', models.CharField(max_length=3, verbose_name='Сыгрно игр')),
                ('player_winrate', models.CharField(max_length=3, verbose_name='Винрейт игрока')),
                ('fraction_name', models.CharField(max_length=20, verbose_name='Фракция')),
                ('fraction_games', models.CharField(max_length=3, verbose_name='Сыгрно игр')),
                ('fraction_winrate', models.CharField(max_length=3, verbose_name='Винрейт фракции')),
            ],
        ),
        migrations.DeleteModel(
            name='WinrateFractionsStats',
        ),
        migrations.DeleteModel(
            name='WinratePlayersStats',
        ),
    ]
