# Generated by Django 4.0.4 on 2022-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_winratestats_delete_winratefractionsstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinrateFractionsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фракция')),
                ('games', models.CharField(max_length=3, verbose_name='Сыгрно игр')),
                ('winrate', models.CharField(max_length=3, verbose_name='Винрейт фракции')),
            ],
        ),
        migrations.CreateModel(
            name='WinratePlayersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Игрок')),
                ('games', models.CharField(max_length=3, verbose_name='Сыгрно игр')),
                ('winrate', models.CharField(max_length=3, verbose_name='Винрейт игрока')),
            ],
        ),
        migrations.DeleteModel(
            name='WinrateStats',
        ),
    ]
