# Generated by Django 4.0.4 on 2022-06-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_winratefractionsstats_winrateplayersstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winratefractionsstats',
            name='winrate',
            field=models.CharField(max_length=4, verbose_name='Винрейт фракции'),
        ),
    ]
