# Generated by Django 4.0.4 on 2022-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_winratefractionsstats_winrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winrateplayersstats',
            name='winrate',
            field=models.CharField(max_length=4, verbose_name='Винрейт игрока'),
        ),
    ]
