# Generated by Django 4.0.5 on 2022-10-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FractionsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Фракция')),
                ('games', models.BigIntegerField(verbose_name='Финалок фракции')),
                ('winrate', models.BigIntegerField(verbose_name='Винрейт фракции')),
                ('rating', models.BigIntegerField(verbose_name='Рейтинг фракции')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'винрейт фракции',
                'verbose_name_plural': 'Винрейт фракций',
                'ordering': ['-rating', '-games'],
            },
        ),
        migrations.CreateModel(
            name='PlayersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Игрок')),
                ('games', models.BigIntegerField(verbose_name='Финалок игрока')),
                ('winrate', models.BigIntegerField(verbose_name='Винрейт игрока')),
                ('rating', models.BigIntegerField(verbose_name='Рейтинг игрока')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'винрейт игрока',
                'verbose_name_plural': 'Винрейт игроков',
                'ordering': ['-rating', '-games'],
            },
        ),
    ]
