# Generated by Django 4.0.5 on 2022-10-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_fractionsstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionsdescriptions',
            name='fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.fractionsstats', verbose_name='Фракция'),
        ),
        migrations.AlterField(
            model_name='playersdescriptions',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.playersstats', verbose_name='Игрок'),
        ),
    ]
