# Generated by Django 4.0.5 on 2022-10-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_fractionsdescriptions_fraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersdescriptions',
            name='player',
        ),
        migrations.AddField(
            model_name='fractionsstats',
            name='description',
            field=models.TextField(default='История оказалась пуста ¯\\_(ツ)_/¯', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='playersstats',
            name='description',
            field=models.TextField(default='История оказалась пуста ¯\\_(ツ)_/¯', verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='FractionsDescriptions',
        ),
        migrations.DeleteModel(
            name='PlayersDescriptions',
        ),
    ]
