# Generated by Django 4.0.5 on 2022-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='type',
            field=models.CharField(default='Сингл', max_length=150, verbose_name='Тип карты'),
        ),
    ]
